# Generated by Django 5.1.3 on 2024-11-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_canvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='height',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='canvas',
            name='pixel_edit_interval',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='canvas',
            name='width',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='canvas',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
