# Generated by Django 4.2.17 on 2024-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_canvas_height_canvas_pixel_edit_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='last_edit_timestamps',
            field=models.JSONField(default=dict),
        ),
    ]
