# Generated by Django 5.1.3 on 2024-12-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_canvas_last_edit_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvas',
            name='contributions',
            field=models.JSONField(default=dict),
        ),
    ]
